### ISSUE TITLE
Fix filenames in luarocks version of lua-quickcheck

### ISSUE THREAD

**Issue by ratanvarghese** [Primordus/lua-quickcheck#17]
After installing lua-quickcheck from luarocks and attempting to run `lqc --help` I ran into the following error:

`module lqc.generators.table not found:No LuaRocks module found for lqc.generators.table`

I noticed that in the`generators` folder of the luarocks version of lua-quickcheck, the filenames were not consistent with the ones used on github.

`lqc --help` seemed to run properly after I changed the following filenames in the `generators` folder:
+ `tbl.lua` to `table.lua`
+ `str.lua` to `string.lua`

 If I had to guess, the inconsistent filenames are probably caused by these lines in the rockspec:

    ['lqc.generators.str'] = 'lqc/generators/string.lua',
    ['lqc.generators.tbl'] = 'lqc/generators/table.lua',

As of the time of this writing I have not used anything in lua-quickcheck other than `lqc --help`, so I don't know what problems renaming these files might cause.

**Comment by luc-tielen** [comment]
Hi, thanks for reporting this issue!

I will look into it the following few days, it's been a while since I last used this library 😅

**Comment by luc-tielen** [comment]
@ratanvarghese so I think I fixed it (though Travis CI seems to disagree, will fix that later).
I pushed a new `v0.2-4`, can you try if that 1 works for you?

I installed locally via luarocks and tried it out:
```
$ ~/.luarocks/bin/lqc spec/fixtures/examples
Random seed = 1553117722
........................................................................................................................................................................................................
200 tests, 0 failures, 0 skipped.
```

Your intuition was right, somehow I had some wrong filenames in there!
I will keep the issue open until I manage to fix CI somehow (which hopefully won't be too painful 😅.)

**Comment by ratanvarghese** [comment]
I've tried the new version, and it works on my machine. Thanks for the prompt fix!
