### ISSUE TITLE
Is there "getting started" documentation?  Or documentation for clients?

### ISSUE THREAD

**Issue by nrnrnr** [Primordus/lua-quickcheck#20]
I found #15, but what seems to be there is *comprehensive* documentation of every function, including internals that I might wish not to know about.  To get started, I'd just like to pull out the basic API calls needed to specify a generator and a property.  Also, just the basic model---this library looks more stateful than the Haskell or other QuickCheck things I am used to.

What would you recommend to identify the key API points a new user would need in order to get started?  What would I actually put in a file passed to lqc on the command line?

**Comment by luc-tielen** [comment]
Right, this is a good point. Maybe it is a good idea to add an introduction markdown file (or another section to the README) describing the basic stuff.
The examples in https://github.com/luc-tielen/lua-quickcheck/tree/master/spec/fixtures/examples showcase the basic API for non-stateful properties but for FSMs right now you need to look at the specs..

Regarding statefulness, what do you mean by this? The generators themselves?

**Comment by nrnrnr** [comment]
The command you put into #19 was a good start---I have a somewhat clearer idea what is going on.  That and a quick guide to specifying generators would be a good jumping-off point.

Regarding statefulness, the `property` function seems to have a side effect on global state, rather than passing a property to a quickcheck function.  I think I was looking for an API more like Haskell.  Now, having studied the example, I see that the imperative code in the examples showcase is meant to *look* declarative.

Incidentally, an additional part of the documentation would be to point to the set of names that are bound into the global environment in a spec file.  I would have expected to have to `require` the `lqc` API, but it looks as if such functions as `property` and `int` are just sitting there waiting to be called.

**Comment by luc-tielen** [comment]
I had some time to write out some extra docs today (see #21).

You are completely right about statefulness, `property` and `fsm` register themselves to a global array of properties before the runner starts checking them all. I mainly tried to be declarative in the look and feel when using the library (and this is now mentioned in the README).

Thanks for pointing out some stuff that wasn't immediately obvious to me after implementing it fully 😄.
If you still feel stuff is missing or needs to be more clarified, feel free to open a issue/PR and add the missing pieces 😉.
