### ISSUE TITLE
Look into different CI setup

### ISSUE THREAD

**Issue by luc-tielen** [Primordus/lua-quickcheck#22]
Travis times out a lot lately for some of the fsm properties if they don't generate any output.

Maybe consider other CIs (Circle CI, ...?) or add a workaround script that outputs a character every minute or so..?

**Comment by ligurio** [comment]
I think Github Actions will be more than enough here. What do you think?

**Comment by luc-tielen** [comment]
I think so too, I don't think github actions already existed (or were mature enough) when I created this issue. 

If you want, you could create a PR 😄  but there's not many changes nowadays so it's not super critical.

**Comment by ligurio** [comment]
> If you want, you could create a PR smile but there's not many changes nowadays so it's not super critical.

https://github.com/luc-tielen/lua-quickcheck/pull/27

**Comment by luc-tielen** [comment]
That was fast 😲 . I will look into your changes later. Thanks!
