### ISSUE TITLE
It is unclear how to use lqc with other testing frameworks

### ISSUE THREAD

**Issue by ligurio** [Primordus/lua-quickcheck#29]
I'm using testing framework (`luatest`) that provides mechanisms for setup/teardown and a number of asserts.
To make testing more rigorous I want to use `lqc` but from documentation/examples/readme it is not clear how to do it.
`lqc` has it's own keywords that should be used to mark test with properties and `luatest` uses global functions and asserts.
In both cases tool must be an executor for script with tests.

Could you help here?

**Comment by ligurio** [comment]
I'll try to answer: yes, it's possible. Examples with using lqc with busted in `spec` directory, [for example](https://github.com/luc-tielen/lua-quickcheck/blob/master/spec/quickcheck_spec.lua#L43-L56):
```lua
    it('should continue to check if a constraint of property is not met', function()
      local spy_check = spy.new(function() return true end)
      local spy_implies = spy.new(function() return false end)
      property 'test property' {
        generators = {},
        check = spy_check,
        implies = spy_implies
      }

      lqc.check()
      local expected = lqc.numtests
      assert.spy(spy_check).was.not_called()
      assert.spy(spy_implies).was.called(expected)
    end)
```

**Comment by luc-tielen** [comment]
I did not focus on integration with other test frameworks at the time. In the test suite of this library I used busted to run the test suite. The checking happens via `lqc.check()`;  `lqc` manages it's own test results.

**Comment by ligurio** [comment]
With implicit imports of `lqc` modules it works fine:
Example of test that runs with `luatest`:

```lua
local any = require 'lqc.generators.any'
local lqc = require 'lqc.quickcheck'
local property = require 'lqc.property'
local random = require 'lqc.random'
local r = require 'lqc.report'

local g = t.group()

-- {{{ Setup / teardown

g.before_all(function()
    -- Setup.
end)

g.after_all(function()
    -- Tear down.
end)

g.before_each(function()


    -- lqc initialization
    random.seed()
    lqc.init(100, 100)
    lqc.properties = {}
    r.report = function() end
end)

g.after_each(function()
    --
end)

-- {{{ set_get_value

g.test_set_get_value = function()
    property 'set and get in configuration' {
        generators = { any() },
        check = function(v)
            g.conf_client:set('a', v)
        end
    }
    lqc.check()
    t.assert_equals(1, #lqc.properties)
end

-- }}} set_get_value
```

To run: `luatest ./test/conf_test.lua`

**Comment by luc-tielen** [comment]
Very cool. Thanks for documenting this.
